import type { Drill } from "./schema";

/**
 * The drill library — the single source of truth every plan (pre-built or
 * generated) draws from. Drills are reused across many plans with different
 * emphasis rather than duplicated per plan; volume comes from composition
 * across category × movement × playstyle × equipment × level tags, not from
 * hand-writing near-duplicate entries.
 */

const shared: Drill[] = [
  {
    id: "warmup-dynamic-mobility",
    name: "Dynamic Mobility Flow",
    shortDescription: "Leg swings, walking lunges with a twist, and high-knee marches to open the hips and raise heart rate.",
    execution: [
      "10 leg swings each direction, each leg, holding a wall or post for balance.",
      "10 walking lunges, rotating your torso toward the front leg at the bottom of each step.",
      "20m of high-knee marching, driving the knee to hip height each step.",
    ],
    footballWhy: "A cold hip or ankle is where a training session's first pulled muscle happens — this gets the exact ranges of motion you're about to use moving well before you ask them to work hard.",
    coachingCue: "Move through the full range, but stay controlled — this isn't a stretch to hold, it's motion to build.",
    commonMistake: "Rushing through it in under 3 minutes. Give it the full 5-6 minutes; it's not filler, it's injury prevention.",
    prescription: { sets: 1, reps: "full circuit", restSeconds: 0, effortRPE: 3 },
    progression: { label: "Progression", change: "Add a resistance band around the ankles for the lunges and marches." },
    regression: { label: "Regression", change: "Drop the twist/rotation and just perform the base movement." },
    category: "speed-agility",
    movementPatterns: ["rotation", "change-of-direction"],
    positionGroups: ["goalkeepers", "defenders", "midfielders", "attackers"],
    playstyles: [],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
    isWarmup: true,
  },
  {
    id: "warmup-activation-sprints",
    name: "Activation Strides",
    shortDescription: "A short set of build-up strides from jog to near-sprint to switch on the nervous system.",
    execution: [
      "Jog 10m, building smoothly to 80% top speed by 30m, then ease off.",
      "Walk back to the start as full recovery.",
      "Repeat, reaching a touch faster each rep.",
    ],
    footballWhy: "The first real sprint of a session is when a hamstring is most vulnerable if the body hasn't been told it's about to sprint — this is that warning shot at low risk.",
    coachingCue: "Build the speed smoothly — no rep should feel like an explosive start from zero.",
    commonMistake: "Going 100% on the first rep. Save your fastest rep for last, not first.",
    prescription: { sets: 4, reps: "30m build-up", restSeconds: 30, effortRPE: 5 },
    progression: { label: "Progression", change: "Add a single 90% effort rep at the end once fully warm." },
    regression: { label: "Regression", change: "Cap builds at 60% effort and shorten to 20m." },
    category: "speed-agility",
    movementPatterns: ["acceleration", "sprint-mechanics"],
    positionGroups: ["goalkeepers", "defenders", "midfielders", "attackers"],
    playstyles: [],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
    isWarmup: true,
  },
  {
    id: "warmup-activation-band",
    name: "Band Hip Activation",
    shortDescription: "Lateral band walks and monster walks to wake up the glutes before loaded or explosive work.",
    execution: [
      "Place a light resistance band around the ankles or just above the knees.",
      "Side-step 10 steps in one direction keeping knees bent and tension on the band, then 10 back.",
      "Follow with 10 diagonal 'monster walk' steps each direction.",
    ],
    footballWhy: "Weak glute activation is a common, quiet cause of knee and lower-back strain once real load or sprinting starts — this switches them on cheaply beforehand.",
    coachingCue: "Keep constant tension on the band the entire time — don't let your feet drift back together.",
    commonMistake: "Standing tall. Stay in a quarter-squat position throughout, or the band does nothing.",
    prescription: { sets: 2, reps: "10 each direction", restSeconds: 20, effortRPE: 3 },
    progression: { label: "Progression", change: "Use a heavier-resistance band." },
    regression: { label: "Regression", change: "Perform without a band, focusing purely on the knee-bent position." },
    category: "strength",
    movementPatterns: ["bracing"],
    positionGroups: ["goalkeepers", "defenders", "midfielders", "attackers"],
    playstyles: [],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
    isWarmup: true,
  },
  {
    id: "cooldown-static-stretch",
    name: "Full-Body Static Stretch",
    shortDescription: "Held stretches for the hips, hamstrings, calves, and shoulders to close out the session.",
    execution: [
      "Hold a hamstring, quad, and hip-flexor stretch on each leg for 30 seconds apiece.",
      "Hold a calf stretch against a wall for 30 seconds each side.",
      "Finish with a cross-body shoulder stretch, 20 seconds each arm.",
    ],
    footballWhy: "Tissue that's been repeatedly loaded and shortened all session settles better and recovers faster overnight when it's returned to a full, relaxed length before you stop.",
    coachingCue: "Breathe slowly and let each stretch ease deeper over the 30 seconds — don't force the first few seconds.",
    commonMistake: "Bouncing in the stretch. Static means still; save any bouncing movement for the warm-up, not here.",
    prescription: { sets: 1, reps: "full circuit", restSeconds: 0, effortRPE: 1 },
    progression: { label: "Progression", change: "Extend each hold to 45 seconds." },
    regression: { label: "Regression", change: "Hold each stretch for 15 seconds instead of 30." },
    category: "endurance",
    movementPatterns: ["bracing"],
    positionGroups: ["goalkeepers", "defenders", "midfielders", "attackers"],
    playstyles: [],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
    isCooldown: true,
  },
  {
    id: "cooldown-easy-jog",
    name: "Easy Jog & Walk-Down",
    shortDescription: "A few minutes of light jogging tapering to a walk, bringing the heart rate down gradually.",
    execution: [
      "Jog at a conversational pace for 3 minutes.",
      "Walk for 2 minutes, breathing deeply.",
    ],
    footballWhy: "Stopping dead after high-intensity work leaves blood pooled in the legs and can leave you light-headed — an easy taper keeps circulation moving while heart rate drops.",
    coachingCue: "You should be able to hold a full conversation the entire time.",
    commonMistake: "Skipping this because it feels pointless after a hard session — it's precisely the hard sessions where it matters most.",
    prescription: { sets: 1, reps: "5 minutes", restSeconds: 0, effortRPE: 2 },
    progression: { label: "Progression", change: "No change needed — this stays gentle regardless of level." },
    regression: { label: "Regression", change: "Walk the entire 5 minutes instead of jogging." },
    category: "endurance",
    movementPatterns: ["deceleration"],
    positionGroups: ["goalkeepers", "defenders", "midfielders", "attackers"],
    playstyles: [],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
    isCooldown: true,
  },
  {
    id: "cooldown-breathing-reset",
    name: "Breathing Reset",
    shortDescription: "Slow diaphragmatic breathing lying down to shift out of a training state and speed recovery.",
    execution: [
      "Lie on your back, knees bent, one hand on your chest and one on your stomach.",
      "Breathe in through the nose for 4 counts, feeling the stomach hand rise more than the chest hand.",
      "Exhale slowly for 6 counts. Repeat for 2 minutes.",
    ],
    footballWhy: "Recovery between sessions starts the moment the nervous system downshifts out of a trained, adrenaline-up state — this is a deliberate, fast way to trigger that shift.",
    coachingCue: "The exhale should be longer than the inhale every time — that's what does the work.",
    commonMistake: "Breathing shallow and fast into the chest instead of deep into the stomach.",
    prescription: { sets: 1, reps: "2 minutes", restSeconds: 0, effortRPE: 1 },
    progression: { label: "Progression", change: "Extend to 4 minutes." },
    regression: { label: "Regression", change: "Shorten to 1 minute if 2 feels long." },
    category: "endurance",
    movementPatterns: ["bracing"],
    positionGroups: ["goalkeepers", "defenders", "midfielders", "attackers"],
    playstyles: [],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
    isCooldown: true,
  },
];

const goalkeepers: Drill[] = [
  {
    id: "gk-plank-catch",
    name: "Plank-to-Catch Stability Hold",
    shortDescription: "Hold a plank while catching and releasing a ball to build core stability under load.",
    execution: [
      "Set up in a forearm plank with a partner (or wall) 2m in front of you.",
      "Have the ball thrown to you; catch and return it without letting your hips sag or twist.",
      "Reset your plank position between each throw if needed.",
    ],
    footballWhy: "A goalkeeper's core has to stay rigid while the arms move independently to catch off-center crosses and shots — this trains exactly that separation.",
    coachingCue: "Keep a straight line from shoulders to heels the entire time — the ball should move, not your torso.",
    commonMistake: "Letting the hips drop as fatigue sets in, which is the first sign the plank has already broken down.",
    prescription: { sets: 3, reps: "30s", restSeconds: 45, effortRPE: 5 },
    progression: { label: "Progression", change: "Extend holds to 45s and use a heavier medicine ball." },
    regression: { label: "Regression", change: "Perform from a knee plank instead of a full plank." },
    category: "strength",
    movementPatterns: ["bracing"],
    positionGroups: ["goalkeepers"],
    playstyles: ["sweeper-keeper", "shot-stopper"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "gk-overhead-throw",
    name: "Overhead Med-Ball Throw",
    shortDescription: "Explosive overhead throws to build the upper-body power that punches away crosses under pressure.",
    execution: [
      "Stand with feet shoulder-width apart, holding a medicine ball at chest height.",
      "Drive through the legs and throw the ball explosively overhead and forward.",
      "Retrieve, reset, and repeat with full intent on every rep.",
    ],
    footballWhy: "Punching a cross clear under a striker's pressure is a full-body explosive movement, not just an arm action — this trains the same leg-to-arm power chain.",
    coachingCue: "Drive the throw from your legs first — the arms finish the movement, they don't start it.",
    commonMistake: "Throwing purely from the shoulders with no leg drive, which caps how much power you can generate.",
    prescription: { sets: 3, reps: "10", restSeconds: 60, effortRPE: 7 },
    progression: { label: "Progression", change: "Increase medicine ball weight or add a small jump into the throw." },
    regression: { label: "Regression", change: "Use a lighter ball and throw from a seated position to isolate the arms." },
    category: "strength",
    movementPatterns: ["rotation"],
    positionGroups: ["goalkeepers"],
    playstyles: ["shot-stopper"],
    equipment: "minimal",
    levels: ["amateur", "advanced"],
  },
  {
    id: "gk-single-leg-bridge",
    name: "Single-Leg Glute Bridge",
    shortDescription: "Build hip strength for a more powerful push-off into a dive.",
    execution: [
      "Lie on your back, one knee bent with foot flat, other leg extended straight.",
      "Drive through the planted heel to lift your hips until your body forms a straight line.",
      "Lower with control and repeat, then switch legs.",
    ],
    footballWhy: "Every diving save starts with a push-off from one leg — this isolates and strengthens exactly that push-off muscle group.",
    coachingCue: "Squeeze the glute at the top of every rep, don't just let momentum carry you there.",
    commonMistake: "Arching the lower back to gain height instead of driving through the hip.",
    prescription: { sets: 3, reps: "12 each leg", restSeconds: 45, effortRPE: 5 },
    progression: { label: "Progression", change: "Elevate the planted foot on a low box, or add a band above the knees." },
    regression: { label: "Regression", change: "Perform a standard two-leg bridge instead of single-leg." },
    category: "strength",
    movementPatterns: ["bracing"],
    positionGroups: ["goalkeepers"],
    playstyles: ["sweeper-keeper", "shot-stopper"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "gk-ladder-lateral",
    name: "Ladder Footwork: Lateral Shuffle",
    shortDescription: "Quick lateral steps through an agility ladder to sharpen footwork before setting for a save.",
    execution: [
      "Stand side-on at one end of the ladder.",
      "Step laterally through each rung with quick, light contacts, staying low.",
      "Turn and repeat back through in the opposite direction.",
    ],
    footballWhy: "The tiny adjustment steps a keeper takes to get perfectly set before a shot come from exactly this kind of quick, light footwork.",
    coachingCue: "Stay on the balls of your feet — you should barely hear your feet touch the ground.",
    commonMistake: "Looking down at the ladder instead of keeping your eyes up, which you'll never get away with in a real game.",
    prescription: { sets: 4, reps: "20s", restSeconds: 40, effortRPE: 5 },
    progression: { label: "Progression", change: "Add a reaction call (left/right) mid-ladder that changes your exit direction." },
    regression: { label: "Regression", change: "Slow the pace and focus purely on clean rung contacts." },
    category: "speed-agility",
    movementPatterns: ["change-of-direction"],
    positionGroups: ["goalkeepers"],
    playstyles: ["sweeper-keeper", "shot-stopper"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "gk-reaction-drop",
    name: "Reaction Ball Drops",
    shortDescription: "A partner drops an unpredictably bouncing ball for you to react to and catch.",
    execution: [
      "Kneel or crouch 2-3m from a partner holding a reaction ball (or any irregularly-shaped ball).",
      "Partner drops it without warning; react and catch it before the second bounce.",
      "Reset and repeat, varying the drop side each time.",
    ],
    footballWhy: "A deflected shot behaves unpredictably in exactly this way — training the reaction, not just the catch, is what actually transfers.",
    coachingCue: "Stay relaxed and ready rather than tensed and guessing — let your eyes trigger the movement.",
    commonMistake: "Anticipating a side based on the partner's habits instead of reacting to the actual bounce.",
    prescription: { sets: 3, reps: "10", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Increase distance to 4m so you have less reaction time." },
    regression: { label: "Regression", change: "Use a normal ball with a predictable bounce first." },
    category: "speed-agility",
    movementPatterns: ["change-of-direction"],
    positionGroups: ["goalkeepers"],
    playstyles: ["shot-stopper"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "gk-explosive-first-step",
    name: "Explosive First-Step Close-Down",
    shortDescription: "Short, sharp bursts off your line to close down space quickly.",
    execution: [
      "Start on your goal line in a ready stance.",
      "On a cue, explode forward 5m as fast as possible.",
      "Chop your steps down to a controlled stop at the end, as if closing an attacker down.",
    ],
    footballWhy: "A sweeper-keeper's value comes from repeatedly winning the race to loose balls outside the box — this is that exact race, trained in isolation.",
    coachingCue: "The first two steps are everything — drive them low and hard rather than standing up too early.",
    commonMistake: "Standing tall on the very first step, which kills acceleration before it starts.",
    prescription: { sets: 4, reps: "10", restSeconds: 45, effortRPE: 7 },
    progression: { label: "Progression", change: "Start from a lateral shuffle rather than a static stance." },
    regression: { label: "Regression", change: "Reduce the distance to 3m." },
    category: "speed-agility",
    movementPatterns: ["acceleration"],
    positionGroups: ["goalkeepers"],
    playstyles: ["sweeper-keeper"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "gk-shuttle-sprints",
    name: "Interval Shuttle Sprints Between Posts",
    shortDescription: "Short recovery sprints between the goalposts to build match-speed endurance.",
    execution: [
      "Sprint from one post to the other (roughly 7m) and touch the ground.",
      "Jog back to the start as recovery.",
      "Repeat for the full set, keeping every sprint at genuine effort.",
    ],
    footballWhy: "A sweeper-keeper covers the width of the box repeatedly across 90 minutes — this builds the aerobic base to do that without the last sprint of the match being slower than the first.",
    coachingCue: "Match your first rep's speed on your last rep — that's the real measure of this drill working.",
    commonMistake: "Sprinting hard early and coasting later instead of pacing evenly across the set.",
    prescription: { sets: 8, reps: "15m", restSeconds: 30, effortRPE: 7 },
    progression: { label: "Progression", change: "Extend to 12 reps or reduce rest to 20s." },
    regression: { label: "Regression", change: "Reduce to 6 reps with 45s rest." },
    category: "endurance",
    movementPatterns: ["sprint-mechanics"],
    positionGroups: ["goalkeepers"],
    playstyles: ["sweeper-keeper"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "gk-dive-recover",
    name: "Repeated Dive-and-Recover Circuit",
    shortDescription: "Low dive, get back to your feet, reset, repeat — building recovery speed after going to ground.",
    execution: [
      "From a ready stance, dive low to one side onto a soft surface.",
      "Get back to your feet as quickly as possible into a ready stance.",
      "Immediately dive to the opposite side and repeat.",
    ],
    footballWhy: "A save is only half the job — a shot-stopper who's slow to reset is exposed on the rebound, which this circuit directly trains against.",
    coachingCue: "Get your hands underneath you immediately on landing — that's what makes the recovery fast.",
    commonMistake: "Standing up in stages instead of driving straight back into a ready stance.",
    prescription: { sets: 4, reps: "8", restSeconds: 60, effortRPE: 7 },
    progression: { label: "Progression", change: "Add a reaction catch immediately after each recovery." },
    regression: { label: "Regression", change: "Reduce to 5 reps and allow a full stand-up between dives." },
    category: "endurance",
    movementPatterns: ["jump-land"],
    positionGroups: ["goalkeepers"],
    playstyles: ["shot-stopper"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "gk-wall-catching",
    name: "Two-Handed Catching Against a Wall",
    shortDescription: "Repeated basic handling reps to groove clean catching technique.",
    execution: [
      "Stand 3-4m from a flat wall.",
      "Throw the ball against the wall and catch the rebound with both hands, fingers spread, thumbs together behind the ball.",
      "Reset and repeat continuously.",
    ],
    footballWhy: "Every save starts with this exact hand shape — grooving it in a low-pressure repetition is what makes it automatic under a real shot.",
    coachingCue: "Thumbs and index fingers should form a 'W' shape behind the ball on every catch.",
    commonMistake: "Catching with flat palms and straight fingers, which lets the ball squirm through on a firmer shot.",
    prescription: { sets: 3, reps: "15", restSeconds: 30, effortRPE: 3 },
    progression: { label: "Progression", change: "Increase throw speed and vary the height of each throw." },
    regression: { label: "Regression", change: "Increase distance from the wall to slow the rebound down." },
    category: "position-specific",
    movementPatterns: ["bracing"],
    positionGroups: ["goalkeepers"],
    playstyles: ["sweeper-keeper", "shot-stopper"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "gk-distribution-accuracy",
    name: "Long & Short Distribution Accuracy",
    shortDescription: "Alternate short throws and long goal-kicks at targets to build range and accuracy.",
    execution: [
      "Set up two targets — one 15m away, one 30m+ away.",
      "Throw or roll to the short target with pace and precision.",
      "Strike a goal-kick or long throw to the far target, alternating between the two for the full set.",
    ],
    footballWhy: "A sweeper-keeper who can't hit both targets reliably becomes a liability the moment a team tries to build out from the back through them.",
    coachingCue: "Pick your target before you strike the ball, not while the ball is already in flight.",
    commonMistake: "Only practicing the long option — the short, quick release under pressure is used far more often in a real match.",
    prescription: { sets: 3, reps: "8 each", restSeconds: 45, effortRPE: 5 },
    progression: { label: "Progression", change: "Add a passive defender jogging toward you to simulate a press." },
    regression: { label: "Regression", change: "Move the far target closer until accuracy is consistent." },
    category: "position-specific",
    movementPatterns: ["rotation"],
    positionGroups: ["goalkeepers"],
    playstyles: ["sweeper-keeper"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "gk-low-diving-save",
    name: "Low Diving Save Repetitions",
    shortDescription: "Technique-focused low dives onto a soft surface, alternating sides.",
    execution: [
      "Start in a ready stance with a partner or coach ready to roll/throw a low ball to either side.",
      "Dive low, leading with the hip, and collect the ball at the lowest possible point.",
      "Recover to your feet and reset before the next rep.",
    ],
    footballWhy: "The low dive is the save shot-stoppers make most often — grooving clean technique here directly reduces low shots squirming under the body.",
    coachingCue: "Lead the dive with your hip and bottom hand, not your top hand reaching alone.",
    commonMistake: "Diving forward instead of sideways, which leaves the ball unsupported underneath the body.",
    prescription: { sets: 3, reps: "10 each side", restSeconds: 60, effortRPE: 6 },
    progression: { label: "Progression", change: "Increase the speed and unpredictability of the service." },
    regression: { label: "Regression", change: "Start from a kneeling position to isolate the hand technique first." },
    category: "position-specific",
    movementPatterns: ["jump-land"],
    positionGroups: ["goalkeepers"],
    playstyles: ["shot-stopper"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
];

const defenders: Drill[] = [
  {
    id: "def-goblet-squat",
    name: "Goblet Squat",
    shortDescription: "Build lower-body strength to win physical duels against attackers.",
    execution: [
      "Hold a dumbbell or kettlebell vertically at chest height.",
      "Squat down keeping your chest up and knees tracking over your toes until thighs are parallel to the ground.",
      "Drive back up through your heels to standing.",
    ],
    footballWhy: "Winning a shoulder-to-shoulder duel or holding your ground against a driving run comes from exactly this kind of lower-body strength base.",
    coachingCue: "Keep your weight in your heels and mid-foot the entire way down.",
    commonMistake: "Letting the knees cave inward at the bottom of the squat, which is where non-contact knee injuries often start.",
    prescription: { sets: 3, reps: "10", restSeconds: 75, effortRPE: 6 },
    progression: { label: "Progression", change: "Increase load or switch to a barbell back squat." },
    regression: { label: "Regression", change: "Perform bodyweight-only, focusing purely on depth and knee tracking." },
    category: "strength",
    movementPatterns: ["bracing"],
    positionGroups: ["defenders"],
    playstyles: ["ball-playing-cb", "aggressive-stopper", "overlapping-wing-back", "inverted-full-back"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "def-single-leg-deadlift",
    name: "Single-Leg Deadlift",
    shortDescription: "Build hamstring strength and balance for stability while tackling.",
    execution: [
      "Stand on one leg holding a light dumbbell in the opposite hand.",
      "Hinge at the hip, extending the free leg straight behind you as your torso lowers toward parallel.",
      "Squeeze the standing glute and hamstring to return upright.",
    ],
    footballWhy: "A composed first touch and pass out of the back line both depend on single-leg balance under a bit of contact — this builds that directly.",
    coachingCue: "Keep your hips square to the ground throughout — don't let them rotate open.",
    commonMistake: "Rounding the lower back to reach further down instead of stopping the hinge at your natural range.",
    prescription: { sets: 3, reps: "8 each leg", restSeconds: 60, effortRPE: 6 },
    progression: { label: "Progression", change: "Increase the dumbbell weight." },
    regression: { label: "Regression", change: "Perform bodyweight-only with a fingertip touch on a wall for balance." },
    category: "strength",
    movementPatterns: ["bracing"],
    positionGroups: ["defenders"],
    playstyles: ["ball-playing-cb"],
    equipment: "minimal",
    levels: ["amateur", "advanced"],
  },
  {
    id: "def-box-jump",
    name: "Box Jump",
    shortDescription: "Explosive leg power to win more headers in both boxes.",
    execution: [
      "Stand facing a sturdy box or platform, feet shoulder-width apart.",
      "Dip into a quarter-squat and explode upward, landing softly on the box with both feet.",
      "Step back down (don't jump down) and reset before the next rep.",
    ],
    footballWhy: "Winning a header at the far post is decided by how high and how quickly you can leave the ground — this is the direct transfer for that.",
    coachingCue: "Land soft, absorbing through the ankles, knees, and hips — a loud landing means you're not decelerating well.",
    commonMistake: "Jumping down off the box instead of stepping down, which adds pointless impact stress with no training benefit.",
    prescription: { sets: 3, reps: "8", restSeconds: 90, effortRPE: 7 },
    progression: { label: "Progression", change: "Increase box height or add a small approach step before jumping." },
    regression: { label: "Regression", change: "Use a lower box or perform a squat jump with no box at all." },
    category: "strength",
    movementPatterns: ["jump-land"],
    positionGroups: ["defenders"],
    playstyles: ["aggressive-stopper"],
    equipment: "minimal",
    levels: ["amateur", "advanced"],
  },
  {
    id: "def-loaded-carry",
    name: "Loaded Carry",
    shortDescription: "Farmer's-carry-style holds for overall strength, grip, and posture.",
    execution: [
      "Hold a heavy dumbbell or kettlebell in each hand at your sides.",
      "Walk a set distance keeping your shoulders back and core braced.",
      "Set the weights down under control at the end, rather than dropping them.",
    ],
    footballWhy: "The posture and total-body bracing this builds is exactly what holds up in a prolonged shoulder-to-shoulder contest for the ball along the touchline.",
    coachingCue: "Imagine a string pulling the crown of your head to the ceiling the whole way — don't let your shoulders round forward.",
    commonMistake: "Letting the weights swing with your stride instead of keeping them still at your sides.",
    prescription: { sets: 3, reps: "30m", restSeconds: 60, effortRPE: 6 },
    progression: { label: "Progression", change: "Increase load or carry distance to 50m." },
    regression: { label: "Regression", change: "Use lighter weights and focus purely on posture over distance." },
    category: "strength",
    movementPatterns: ["bracing"],
    positionGroups: ["defenders"],
    playstyles: ["aggressive-stopper", "overlapping-wing-back"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "def-backpedal-sprint",
    name: "Backpedal-to-Sprint Transition",
    shortDescription: "Practice the defensive footwork of backing off before exploding into a recovery sprint.",
    execution: [
      "Backpedal for 5m in a low defensive stance, staying balanced.",
      "On a cue, plant, turn, and sprint forward or to the side for 10m.",
      "Walk back to the start and repeat.",
    ],
    footballWhy: "This is the exact sequence of jockeying an attacker before they burst past you — training the transition, not just the sprint, is what makes recovery runs actually work in a match.",
    coachingCue: "Keep your hips low during the backpedal so the turn into a sprint is one fluid motion, not two separate steps.",
    commonMistake: "Standing tall during the backpedal, which adds a wasted step to drop back down before you can accelerate.",
    prescription: { sets: 4, reps: "15m", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Add a reaction cue (whistle/color call) that decides the sprint direction." },
    regression: { label: "Regression", change: "Perform the backpedal and sprint as two separate, deliberate phases first." },
    category: "speed-agility",
    movementPatterns: ["deceleration", "change-of-direction"],
    positionGroups: ["defenders"],
    playstyles: ["ball-playing-cb", "aggressive-stopper", "overlapping-wing-back", "inverted-full-back"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "def-1v1-mirror",
    name: "1v1 Mirror Drill",
    shortDescription: "Shadow a partner's lateral movement to sharpen your reactions in one-on-ones.",
    execution: [
      "Face a partner about 2m apart in a small grid.",
      "Partner moves laterally and diagonally; mirror their movement, staying square.",
      "Switch roles after each set.",
    ],
    footballWhy: "Staying square and reactive rather than lunging early is what actually wins a 1v1 duel — this trains the discipline directly.",
    coachingCue: "Stay on the balls of your feet with knees bent — you should be able to change direction instantly at any moment.",
    commonMistake: "Guessing a partner's next move and committing early, which is exactly how attackers get past defenders.",
    prescription: { sets: 4, reps: "20s", restSeconds: 40, effortRPE: 6 },
    progression: { label: "Progression", change: "Add a ball the mover must protect, forcing genuine footwork reads." },
    regression: { label: "Regression", change: "Slow the mover's pace by half until the mirroring is clean." },
    category: "speed-agility",
    movementPatterns: ["change-of-direction"],
    positionGroups: ["defenders"],
    playstyles: ["aggressive-stopper", "inverted-full-back"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "def-quick-feet-press",
    name: "Quick-Feet Pressing Drill",
    shortDescription: "Close down a moving target with sharp, controlled footwork.",
    execution: [
      "Start 5m from a partner dribbling a ball slowly across a small grid.",
      "Close the distance with short, choppy steps rather than long strides.",
      "Arrive under control, showing the dribbler onto your preferred side without diving in.",
    ],
    footballWhy: "An inverted full-back closes down in tight central spaces, not open wide ones — short, quick steps that can stop instantly matter far more here than long-stride speed.",
    coachingCue: "Take smaller steps the closer you get — your very last step before arriving should be your shortest.",
    commonMistake: "Sprinting the whole way in and arriving off-balance, which is exactly when a good dribbler skips past.",
    prescription: { sets: 4, reps: "10", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Have the dribbler attempt a genuine take-on at the end of the close-down." },
    regression: { label: "Regression", change: "Walk through the footwork pattern first with no dribbler present." },
    category: "speed-agility",
    movementPatterns: ["deceleration", "change-of-direction"],
    positionGroups: ["defenders"],
    playstyles: ["inverted-full-back"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "def-sprint-recovery",
    name: "Repeated Sprint Recovery Runs",
    shortDescription: "Short sprints with brief recovery to mirror the stop-start demands of a match.",
    execution: [
      "Sprint 30m at full effort.",
      "Walk back to the start as your recovery.",
      "Repeat for the full set, holding sprint times consistent.",
    ],
    footballWhy: "A wing-back's entire match is this exact pattern, repeated 40-plus times — the fitness to hold pace late is the single biggest separator at this position.",
    coachingCue: "Your last rep's time should be within a second of your first — that's the real target, not just finishing the set.",
    commonMistake: "Turning the walk-back recovery into a jog, which quietly reduces the training effect of the whole set.",
    prescription: { sets: 6, reps: "30m", restSeconds: 45, effortRPE: 8 },
    progression: { label: "Progression", change: "Increase to 8 reps or reduce recovery to 35s." },
    regression: { label: "Regression", change: "Reduce to 4 reps with 60s recovery." },
    category: "endurance",
    movementPatterns: ["sprint-mechanics"],
    positionGroups: ["defenders"],
    playstyles: ["overlapping-wing-back"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "def-long-recovery-sprint",
    name: "Long Recovery Sprint",
    shortDescription: "Sprint back from an advanced position to simulate a defensive recovery run.",
    execution: [
      "Start jogging forward as if you've just overlapped 15m upfield.",
      "On a cue, turn and sprint 40m back toward your own goal at full effort.",
      "Walk back to the start as recovery.",
    ],
    footballWhy: "A wing-back caught upfield when possession turns over has to win this exact race back — training the turn-and-sprint, not just straight-line speed, is what transfers.",
    coachingCue: "Turn your hips fully before your first stride back — a half-turn wastes the first two steps of the sprint.",
    commonMistake: "Jogging the 'forward' phase too slowly, which doesn't replicate the real fatigue of the run this drill is meant to simulate.",
    prescription: { sets: 6, reps: "40m", restSeconds: 60, effortRPE: 8 },
    progression: { label: "Progression", change: "Increase distance to 50m or add a second direction change mid-sprint." },
    regression: { label: "Regression", change: "Reduce distance to 25m." },
    category: "endurance",
    movementPatterns: ["sprint-mechanics", "change-of-direction"],
    positionGroups: ["defenders"],
    playstyles: ["overlapping-wing-back"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "def-jump-recover-circuit",
    name: "Repeated Jump-and-Recover Circuit",
    shortDescription: "Jump, land, reset your position, and repeat to build repeat-effort aerial ability.",
    execution: [
      "Perform a maximal vertical jump, as if attacking a header.",
      "Land, immediately shuffle 2m to the side, and set your feet.",
      "Jump again from the new position — repeat for the full set.",
    ],
    footballWhy: "A center-back rarely wins just one header a match — the ones that matter most often come in quick succession from corners and long spells of pressure.",
    coachingCue: "Reset your feet fully before the next jump — a jump from an unbalanced stance loses most of its height.",
    commonMistake: "Rushing the reset to hit a faster pace, which trades away the actual jump height the drill is meant to train.",
    prescription: { sets: 4, reps: "10", restSeconds: 60, effortRPE: 7 },
    progression: { label: "Progression", change: "Add a partner contesting the landing space to simulate real traffic." },
    regression: { label: "Regression", change: "Reduce to 6 reps per set." },
    category: "endurance",
    movementPatterns: ["jump-land"],
    positionGroups: ["defenders"],
    playstyles: ["aggressive-stopper"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "def-first-pass-accuracy",
    name: "First-Pass Accuracy Under Pressure",
    shortDescription: "Play the first pass out of defense under light pressure to build composure on the ball.",
    execution: [
      "Receive a pass with a passive (then active) defender jogging toward you.",
      "Take one controlling touch away from the pressure.",
      "Play an accurate pass to a target 15-20m away before the defender closes fully.",
    ],
    footballWhy: "A ball-playing center-back's whole value is being trusted with the ball under a striker's press — this drill is that exact moment, rehearsed until it's routine.",
    coachingCue: "Decide where the pass is going before the ball even arrives at your feet.",
    commonMistake: "Taking a heavy first touch that kills your own time on the ball before the pressure even arrives.",
    prescription: { sets: 3, reps: "10", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Use a fully live defender instead of a passive one, and add a second passing option." },
    regression: { label: "Regression", change: "Remove the defender entirely and focus purely on touch and pass accuracy." },
    category: "position-specific",
    movementPatterns: ["rotation"],
    positionGroups: ["defenders"],
    positions: ["CB"],
    playstyles: ["ball-playing-cb"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "def-jockeying-channel",
    name: "Jockeying and Channel Steering",
    shortDescription: "Practice showing an attacker away from goal and into a low-danger area.",
    execution: [
      "Face an attacker with the ball 3-4m away, in a balanced defensive stance.",
      "Jockey backward, staying goal-side and angling your body to show them toward the touchline.",
      "Time a tackle only once they're forced into the low-danger channel.",
    ],
    footballWhy: "Delaying and steering an attacker is what buys your team time to recover shape — a defender who dives in early instead of steering has already lost control of the duel.",
    coachingCue: "Angle your body, don't square it — a square stance invites the attacker to go either way.",
    commonMistake: "Diving into a tackle out of impatience instead of continuing to show the attacker toward the touchline.",
    prescription: { sets: 3, reps: "10", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Use a fully live 1v1 with the attacker trying to beat you on either side." },
    regression: { label: "Regression", change: "Walk through the footwork pattern with no attacker present first." },
    category: "position-specific",
    movementPatterns: ["deceleration", "change-of-direction"],
    positionGroups: ["defenders"],
    playstyles: ["aggressive-stopper", "ball-playing-cb"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "def-overlap-cross-timing",
    name: "Overlap-and-Cross Timing",
    shortDescription: "Time an overlapping run and deliver a first-time or early cross.",
    execution: [
      "Start level with a winger holding the ball wide.",
      "Time a run that overlaps just as the winger's marker is drawn toward the ball.",
      "Receive and deliver a cross into the box in one or two touches.",
    ],
    footballWhy: "An overlapping wing-back who arrives at the wrong moment either offers no option or runs offside — timing the run is as much the skill here as the physical output.",
    coachingCue: "Delay your run half a beat longer than feels natural — most mistimed overlaps arrive too early, not too late.",
    commonMistake: "Sprinting the overlap at full speed the entire way, which arrives too early and gets easily tracked by a covering defender.",
    prescription: { sets: 3, reps: "8", restSeconds: 60, effortRPE: 6 },
    progression: { label: "Progression", change: "Add a recovering defender tracking the overlapping run." },
    regression: { label: "Regression", change: "Walk the timing pattern without a ball first, focusing purely on the run's timing." },
    category: "position-specific",
    movementPatterns: ["acceleration"],
    positionGroups: ["defenders"],
    positions: ["LWB", "RWB", "LB", "RB"],
    playstyles: ["overlapping-wing-back"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "def-tight-space-turn",
    name: "Tight-Space Receiving & Turn",
    shortDescription: "Receive under pressure in a crowded central area and turn into space.",
    execution: [
      "Set up a small grid (roughly 5x5m) with a passive defender inside.",
      "Receive a pass with your back or side to the defender.",
      "Use a single touch to turn away from the pressure into open space.",
    ],
    footballWhy: "An inverted full-back operates centrally in exactly this kind of crowded space — the touch-and-turn under pressure is the core skill the role actually demands.",
    coachingCue: "Check your shoulder before the ball arrives so you already know which way you're turning.",
    commonMistake: "Taking a touch straight ahead into the defender instead of turning away from the pressure.",
    prescription: { sets: 4, reps: "8", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Make the defender fully live rather than passive." },
    regression: { label: "Regression", change: "Remove the defender and rehearse the turn technique alone first." },
    category: "position-specific",
    movementPatterns: ["rotation", "change-of-direction"],
    positionGroups: ["defenders"],
    playstyles: ["inverted-full-back"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
];

const midfielders: Drill[] = [
  {
    id: "mid-bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    shortDescription: "Unilateral leg strength to support repeated acceleration and deceleration.",
    execution: [
      "Stand 60-90cm in front of a bench, resting the top of your back foot on it.",
      "Lower your back knee toward the ground, keeping most weight in the front leg.",
      "Drive up through the front heel to standing.",
    ],
    footballWhy: "Midfielders change speed and direction more times per match than any other position — single-leg strength is what those transitions are actually built on.",
    coachingCue: "Keep your torso mostly upright — leaning far forward turns this into a different, less useful exercise.",
    commonMistake: "Letting the front knee travel far past the toes, which shifts load away from the muscles this drill is meant to target.",
    prescription: { sets: 3, reps: "10 each leg", restSeconds: 60, effortRPE: 6 },
    progression: { label: "Progression", change: "Hold dumbbells at your sides for added load." },
    regression: { label: "Regression", change: "Reduce range of motion and use a wall or chair for balance support." },
    category: "strength",
    movementPatterns: ["bracing"],
    positionGroups: ["midfielders"],
    playstyles: ["deep-lying-playmaker", "box-to-box", "ball-winning-dm", "advanced-playmaker"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "mid-medball-rotational",
    name: "Med-Ball Rotational Throw",
    shortDescription: "Build core power to support a longer, more accurate passing range.",
    execution: [
      "Stand side-on to a wall, holding a medicine ball at hip height.",
      "Rotate your torso away from the wall, then explosively rotate back, releasing the ball at the wall.",
      "Catch the rebound (or reset with a new ball) and repeat, then switch sides.",
    ],
    footballWhy: "A long, accurate switch of play is generated from hip and core rotation, not the arms or leg alone — this trains that rotational power directly.",
    coachingCue: "Let your back foot pivot naturally with the throw — a planted back foot blocks most of the power.",
    commonMistake: "Throwing purely with the arms while keeping the hips still, which caps power and doesn't transfer to a real passing motion.",
    prescription: { sets: 3, reps: "10 each side", restSeconds: 60, effortRPE: 6 },
    progression: { label: "Progression", change: "Increase medicine ball weight or throw distance from the wall." },
    regression: { label: "Regression", change: "Use a lighter ball and slow the rotation down to groove the pattern first." },
    category: "strength",
    movementPatterns: ["rotation"],
    positionGroups: ["midfielders"],
    playstyles: ["deep-lying-playmaker", "advanced-playmaker"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "mid-step-up-knee-drive",
    name: "Step-Up Knee Drive",
    shortDescription: "Explosive power to help close down opponents quickly.",
    execution: [
      "Stand facing a box or sturdy step.",
      "Step up explosively, driving the trail knee up to hip height at the top.",
      "Step back down under control and repeat, then switch the leading leg.",
    ],
    footballWhy: "Winning the ball back starts with an explosive first step to close the passing lane — this trains that exact leg-drive power.",
    coachingCue: "Drive the knee up with real intent, as if you're trying to sprint away the instant you land.",
    commonMistake: "Using momentum to swing the trail leg up instead of actively driving the knee with the hip flexor.",
    prescription: { sets: 3, reps: "10 each leg", restSeconds: 60, effortRPE: 6 },
    progression: { label: "Progression", change: "Increase step height or hold light dumbbells." },
    regression: { label: "Regression", change: "Reduce step height and drop the knee-drive to a controlled march." },
    category: "strength",
    movementPatterns: ["acceleration"],
    positionGroups: ["midfielders"],
    playstyles: ["ball-winning-dm"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "mid-shuttle-direction",
    name: "Shuttle Direction Changes",
    shortDescription: "Quick multidirectional running to prepare for constant changes of direction in midfield.",
    execution: [
      "Set up 3 cones in an L-shape, roughly 5m apart.",
      "Sprint to the first cone, plant, and cut to the second at a sharp angle.",
      "Continue through the pattern, then jog back to reset.",
    ],
    footballWhy: "Central midfield is rarely a straight line — this trains the plant-and-cut mechanics that real match movement actually demands.",
    coachingCue: "Bend the outside knee and lean into the cut — an upright cut is a slow cut.",
    commonMistake: "Rounding off the corners instead of hitting each cone with a sharp, decisive change of direction.",
    prescription: { sets: 4, reps: "1 circuit", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Add a reaction cue that changes the pattern order mid-run." },
    regression: { label: "Regression", change: "Slow the pace to 70% until the footwork pattern is clean." },
    category: "speed-agility",
    movementPatterns: ["change-of-direction"],
    positionGroups: ["midfielders"],
    playstyles: ["deep-lying-playmaker", "box-to-box", "ball-winning-dm", "advanced-playmaker"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "mid-turn-accelerate",
    name: "Turn-and-Accelerate Drill",
    shortDescription: "Practice turning away from pressure and accelerating into open space.",
    execution: [
      "Start facing a partner acting as a passive defender at your back.",
      "Receive a pass, turn sharply away from the defender's side, and accelerate 10m into space.",
      "Reset and repeat, alternating turn direction.",
    ],
    footballWhy: "An advanced playmaker's first touch in tight areas near goal is almost always a turn away from the nearest marker — this is that exact moment, isolated and repeated.",
    coachingCue: "Use your first touch to turn — don't take a flat touch and turn on a second one, which gives the defender time to react.",
    commonMistake: "Turning into the defender's pressure instead of away from it, which is the single most common way possession is lost here.",
    prescription: { sets: 4, reps: "8", restSeconds: 45, effortRPE: 7 },
    progression: { label: "Progression", change: "Make the defender fully live rather than passive." },
    regression: { label: "Regression", change: "Remove the defender and rehearse the turn technique in isolation." },
    category: "speed-agility",
    movementPatterns: ["rotation", "acceleration"],
    positionGroups: ["midfielders"],
    playstyles: ["advanced-playmaker"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "mid-press-recover-shuttle",
    name: "Press-and-Recover Shuttle",
    shortDescription: "Sprint to press, then recover back into defensive shape.",
    execution: [
      "Start in a defensive position 10m from a marked 'ball' cone.",
      "Sprint to press the cone at full effort.",
      "Immediately turn and jog/backpedal back into your original defensive position.",
    ],
    footballWhy: "A single press that isn't followed by a fast recovery just opens the exact gap the opponent wanted — this trains the whole cycle, not just the sprint out.",
    coachingCue: "Treat the recovery run with the same urgency as the press itself — it's not a rest period.",
    commonMistake: "Sprinting hard to press but jogging lazily on the recovery, which defeats the actual point of the drill.",
    prescription: { sets: 6, reps: "1 press+recover", restSeconds: 30, effortRPE: 7 },
    progression: { label: "Progression", change: "Reduce rest to 20s or increase press distance to 15m." },
    regression: { label: "Regression", change: "Reduce to 4 reps with 45s rest." },
    category: "speed-agility",
    movementPatterns: ["acceleration", "deceleration"],
    positionGroups: ["midfielders"],
    playstyles: ["ball-winning-dm", "box-to-box"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "mid-continuous-box-run",
    name: "Continuous Box Run",
    shortDescription: "Sustained running around a marked box to build the deep-lying playmaker's aerobic base.",
    execution: [
      "Mark out a rectangle roughly 30m x 20m.",
      "Jog the perimeter continuously at a steady, sustainable pace.",
      "Maintain the same pace for the full duration without stopping.",
    ],
    footballWhy: "A deep-lying playmaker's influence comes from constant availability across 90 minutes, not sudden bursts — this builds the aerobic engine that makes that possible.",
    coachingCue: "Pick a pace you could hold in conversation and don't let it creep up in the first few minutes.",
    commonMistake: "Starting too fast and fading badly in the second half of the run.",
    prescription: { sets: 1, reps: "15 minutes", restSeconds: 0, effortRPE: 5 },
    progression: { label: "Progression", change: "Extend to 20 minutes or add a ball to dribble around the perimeter." },
    regression: { label: "Regression", change: "Reduce to 10 minutes." },
    category: "endurance",
    movementPatterns: ["sprint-mechanics"],
    positionGroups: ["midfielders"],
    playstyles: ["deep-lying-playmaker"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "mid-hiit-intervals",
    name: "Repeated High-Intensity Intervals",
    shortDescription: "Short, intense running bursts that mirror the demands of covering box-to-box.",
    execution: [
      "Sprint hard for 20m.",
      "Walk for 10 seconds as active recovery.",
      "Repeat continuously for the full set without a long rest between reps.",
    ],
    footballWhy: "A box-to-box midfielder repeats maximal efforts with barely any recovery for the whole match — this is the single most direct simulation of that demand.",
    coachingCue: "Treat every single rep as if it's the only one — the fitness only builds if the intensity stays high throughout.",
    commonMistake: "Letting the effort drop on the middle reps because the finish line of the whole set feels far away.",
    prescription: { sets: 8, reps: "20m", restSeconds: 10, effortRPE: 8 },
    progression: { label: "Progression", change: "Increase to 12 reps or extend sprint distance to 30m." },
    regression: { label: "Regression", change: "Reduce to 6 reps with 20s recovery." },
    category: "endurance",
    movementPatterns: ["sprint-mechanics"],
    positionGroups: ["midfielders"],
    playstyles: ["box-to-box"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "mid-interval-passing",
    name: "Interval Passing Circuit",
    shortDescription: "Passing combinations kept at pace with only short recovery between sets.",
    execution: [
      "Set up 2-3 passing targets or partners in a triangle.",
      "Move the ball around the triangle continuously at one- or two-touch for the work period.",
      "Rest briefly, then repeat.",
    ],
    footballWhy: "A deep-lying playmaker's passing has to stay accurate as fatigue builds, not just when fresh — this trains technique under exactly that condition.",
    coachingCue: "Keep your first touch out of your feet, angled toward your next pass, on every single ball.",
    commonMistake: "Letting passing quality slip in the final minute of the work period instead of holding the same standard throughout.",
    prescription: { sets: 6, reps: "2 minutes", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Add a floating defender inside the triangle to press the ball." },
    regression: { label: "Regression", change: "Reduce the work period to 90 seconds." },
    category: "endurance",
    movementPatterns: ["rotation"],
    positionGroups: ["midfielders"],
    playstyles: ["deep-lying-playmaker"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "mid-first-touch-pressure",
    name: "First-Touch Under Pressure",
    shortDescription: "Receive and release the ball quickly with a defender closing you down.",
    execution: [
      "Receive a pass with a defender starting 5m away and closing as the ball travels.",
      "Take a touch that sets up your next action away from the pressure.",
      "Release a pass or dribble away before the defender arrives.",
    ],
    footballWhy: "An advanced playmaker who can't survive this exact moment gets crowded out of the game entirely, no matter how good their final pass is.",
    coachingCue: "Decide your first touch's direction before the ball arrives, based on where the defender is coming from.",
    commonMistake: "Taking a touch straight down, which gives the defender the extra half-second they need to arrive.",
    prescription: { sets: 4, reps: "8", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Reduce the defender's starting distance to 3m." },
    regression: { label: "Regression", change: "Start with a passive defender before progressing to a live one." },
    category: "position-specific",
    movementPatterns: ["rotation"],
    positionGroups: ["midfielders"],
    playstyles: ["advanced-playmaker"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "mid-switch-of-play",
    name: "Switch-of-Play Accuracy",
    shortDescription: "Practice long diagonal passes to a target to switch the point of attack.",
    execution: [
      "Set up a target zone roughly 35-40m diagonally away.",
      "Strike a long diagonal pass, aiming to have it arrive at a controllable height and pace.",
      "Retrieve and repeat, alternating sides.",
    ],
    footballWhy: "A deep-lying playmaker who can reliably switch play forces the opponent to defend the full width of the pitch, not just one side of it.",
    coachingCue: "Strike through the lower-outside of the ball to get the right combination of height and spin.",
    commonMistake: "Overhitting the pass so it arrives too hot to control, which loses the possession the switch was meant to protect.",
    prescription: { sets: 3, reps: "10", restSeconds: 45, effortRPE: 5 },
    progression: { label: "Progression", change: "Add a 1-2 touch time limit before striking the switch." },
    regression: { label: "Regression", change: "Reduce the target distance until accuracy is consistent." },
    category: "position-specific",
    movementPatterns: ["rotation"],
    positionGroups: ["midfielders"],
    positions: ["CDM", "CM"],
    playstyles: ["deep-lying-playmaker"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "mid-screening-interception",
    name: "Screening & Interception Reads",
    shortDescription: "Read the game and practice cutting out passing lanes before they open.",
    execution: [
      "Position between two attacking players passing the ball between them.",
      "Shift your body position with each pass to stay between the ball and the space you're protecting.",
      "Step in to intercept the moment a pass is under-hit or telegraphed.",
    ],
    footballWhy: "A ball-winning midfielder's best defensive actions come before the pass is even played, from reading body shape and cutting the lane — not from a last-ditch tackle.",
    coachingCue: "Watch the passer's hips and standing foot, not the ball — they tell you where the pass is going half a second early.",
    commonMistake: "Watching the ball only, which means you're always reacting a half-step late instead of anticipating.",
    prescription: { sets: 4, reps: "2 minutes", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Add a third attacking player to increase the passing options to read." },
    regression: { label: "Regression", change: "Slow the passing tempo until the positional reads are consistent." },
    category: "position-specific",
    movementPatterns: ["change-of-direction"],
    positionGroups: ["midfielders"],
    positions: ["CDM"],
    playstyles: ["ball-winning-dm"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "mid-late-arrival-finishing",
    name: "Late-Arrival Box Finishing",
    shortDescription: "Practice arriving late into the box to finish crosses or cutbacks.",
    execution: [
      "Start just outside the box, out of the frame of the near defenders.",
      "Time a run to arrive at the penalty spot just as a cross or cutback is delivered.",
      "Finish first-time or with a minimal touch.",
    ],
    footballWhy: "A midfielder arriving late and unmarked is one of the hardest patterns for a defense to track — timing the run is what actually creates the chance.",
    coachingCue: "Delay your run until the ball-carrier's head is up looking for the cross, not before.",
    commonMistake: "Arriving in the box too early and getting picked up by a covering defender before the ball is even delivered.",
    prescription: { sets: 3, reps: "8", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Add a marking defender tracking the run." },
    regression: { label: "Regression", change: "Practice the finish first from a stationary start before adding the timed run." },
    category: "position-specific",
    movementPatterns: ["acceleration"],
    positionGroups: ["midfielders"],
    playstyles: ["box-to-box", "advanced-playmaker"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
];

const attackers: Drill[] = [
  {
    id: "att-jump-squat",
    name: "Jump Squat",
    shortDescription: "Explosive lower-body power to sharpen your first step into space.",
    execution: [
      "Stand with feet shoulder-width apart, hands on hips or swinging freely.",
      "Squat to a quarter or half depth, then explode upward into a jump.",
      "Land softly and reset before the next rep.",
    ],
    footballWhy: "The half-yard a poacher wins on a defender is generated by exactly this kind of explosive leg power, not top-end speed.",
    coachingCue: "Focus on jump height, not just getting off the ground quickly — full extension is what builds real power.",
    commonMistake: "Rushing straight into the next rep without resetting, which turns this into a fatigue drill instead of a power drill.",
    prescription: { sets: 3, reps: "8", restSeconds: 75, effortRPE: 7 },
    progression: { label: "Progression", change: "Hold light dumbbells or add a resistance band around the hips." },
    regression: { label: "Regression", change: "Perform bodyweight squats without the explosive jump first." },
    category: "strength",
    movementPatterns: ["jump-land"],
    positionGroups: ["attackers"],
    playstyles: ["poacher"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-single-leg-hop",
    name: "Single-Leg Hop",
    shortDescription: "Reactive leg strength and balance to shoot cleanly off either foot.",
    execution: [
      "Stand on one leg with a slight bend in the knee.",
      "Hop forward, landing on the same leg and sticking the landing for a full second before the next hop.",
      "Complete the set on one leg, then switch.",
    ],
    footballWhy: "A clean, balanced plant leg is what separates a well-struck shot from a scuffed one — this trains single-leg control under the exact kind of load a shot places on it.",
    coachingCue: "Stick every landing completely still for a full second before moving again.",
    commonMistake: "Landing and immediately hopping again without control, which trains bouncing rather than the stability this drill is for.",
    prescription: { sets: 3, reps: "10 each leg", restSeconds: 60, effortRPE: 6 },
    progression: { label: "Progression", change: "Hop laterally or onto a low box instead of straight forward." },
    regression: { label: "Regression", change: "Reduce hop distance and focus purely on a stable landing." },
    category: "strength",
    movementPatterns: ["jump-land"],
    positionGroups: ["attackers"],
    playstyles: ["poacher", "inside-forward"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-resistance-band-hold",
    name: "Resistance-Band Hold-Up",
    shortDescription: "Build the upper-body and core strength needed to hold off a defender.",
    execution: [
      "Loop a resistance band around your waist, anchored behind you, held by a partner.",
      "Stand with your back to the resistance, knees bent, as if shielding a ball.",
      "Hold the position, resisting the pull, for the full duration.",
    ],
    footballWhy: "A target man's entire job depends on holding this exact body position under real physical contact long enough for support to arrive.",
    coachingCue: "Get your body weight low and back into the contact — standing tall is what gets you pushed off the ball.",
    commonMistake: "Bracing only with the arms instead of the whole lower body and core.",
    prescription: { sets: 3, reps: "30s", restSeconds: 60, effortRPE: 6 },
    progression: { label: "Progression", change: "Increase band resistance or hold duration to 45s." },
    regression: { label: "Regression", change: "Use a lighter band and reduce hold time to 15s." },
    category: "strength",
    movementPatterns: ["bracing"],
    positionGroups: ["attackers"],
    playstyles: ["target-man"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-full-body-power-circuit",
    name: "Full-Body Power Circuit",
    shortDescription: "Combined explosive strength movements to arrive at match day ready.",
    execution: [
      "Perform 30 seconds each of: jump squats, push-ups, mountain climbers, and standing long jumps.",
      "Move between exercises with minimal rest.",
      "Rest fully after completing all four, then repeat the round.",
    ],
    footballWhy: "A pressing forward needs total-body conditioning that holds up across repeated sprints, not one isolated quality — this circuit trains several at once.",
    coachingCue: "Keep quality high even as fatigue builds across the round — a sloppy rep trains a sloppy pattern.",
    commonMistake: "Slowing to a near-stop between exercises, which turns a conditioning circuit into a series of isolated sets.",
    prescription: { sets: 3, reps: "1 round", restSeconds: 90, effortRPE: 7 },
    progression: { label: "Progression", change: "Add a 5th exercise or reduce transition rest between movements." },
    regression: { label: "Regression", change: "Reduce each exercise to 20 seconds and rest longer between rounds." },
    category: "strength",
    movementPatterns: ["bracing", "jump-land"],
    positionGroups: ["attackers"],
    playstyles: ["pressing-forward"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-sprint-start-standstill",
    name: "Sprint Starts From a Standstill",
    shortDescription: "Practice explosive first steps to beat a defender to the space in behind.",
    execution: [
      "Start in an athletic ready stance, weight slightly forward.",
      "On a cue, drive out into a maximal sprint for 15m.",
      "Walk back to the start and repeat.",
    ],
    footballWhy: "The run in behind that beats an offside line is decided entirely in the first three steps — this isolates exactly that.",
    coachingCue: "Stay low for the first three steps — standing up too early kills acceleration before it builds.",
    commonMistake: "False-stepping backward before driving forward, which wastes the exact time advantage this drill is meant to build.",
    prescription: { sets: 6, reps: "15m", restSeconds: 45, effortRPE: 8 },
    progression: { label: "Progression", change: "Add a reaction cue (visual or verbal) rather than a predictable count." },
    regression: { label: "Regression", change: "Reduce distance to 10m and use a predictable count-based start." },
    category: "speed-agility",
    movementPatterns: ["acceleration"],
    positionGroups: ["attackers"],
    playstyles: ["inside-forward", "poacher"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-change-of-direction-finishing",
    name: "Change-of-Direction Finishing",
    shortDescription: "Sharp cuts to create separation before a shot on goal.",
    execution: [
      "Dribble toward goal at moderate pace.",
      "Execute a sharp cut (inside or outside) around a cone representing a defender.",
      "Accelerate away from the cut and finish on goal within two touches.",
    ],
    footballWhy: "An inside forward's signature move — cutting inside from the touchline — is decided by how sharp this exact change of direction is, not by raw speed alone.",
    coachingCue: "Plant your outside foot firmly and low on the cut — a high plant slows the direction change down.",
    commonMistake: "Slowing down before the cut instead of cutting at pace, which gives a recovering defender time to get across.",
    prescription: { sets: 4, reps: "8", restSeconds: 60, effortRPE: 7 },
    progression: { label: "Progression", change: "Use a live recovering defender instead of a static cone." },
    regression: { label: "Regression", change: "Walk through the cutting footwork before adding pace and a shot." },
    category: "speed-agility",
    movementPatterns: ["change-of-direction"],
    positionGroups: ["attackers"],
    playstyles: ["inside-forward"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-1v1-take-on",
    name: "1v1 Take-On Drill",
    shortDescription: "Practice beating a defender in a confined space using change of pace and direction.",
    execution: [
      "Set up a small grid (roughly 8x5m) with a defender inside.",
      "Attack the defender at pace, using a feint or change of pace to unbalance them.",
      "Beat them and drive out of the far end of the grid under control.",
    ],
    footballWhy: "This is the exact contest an inside forward or winger repeats dozens of times a match — grooving a genuine move here is what makes it reliable under real pressure.",
    coachingCue: "Change pace, not just direction — a slow-fast rhythm unbalances a defender more reliably than direction alone.",
    commonMistake: "Relying on the same move every single rep, which a real defender will read and stop after the first attempt.",
    prescription: { sets: 4, reps: "6", restSeconds: 60, effortRPE: 7 },
    progression: { label: "Progression", change: "Shrink the grid to increase the difficulty of creating separation." },
    regression: { label: "Regression", change: "Use a passive defender first before progressing to a live one." },
    category: "speed-agility",
    movementPatterns: ["change-of-direction", "acceleration"],
    positionGroups: ["attackers"],
    playstyles: ["inside-forward"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-reactive-finishing-cue",
    name: "Reactive Finishing Off a Cue",
    shortDescription: "React to a random visual or verbal cue before finishing a chance.",
    execution: [
      "Stand facing a partner or coach 8-10m away with a ball ready to be played.",
      "On an unpredictable cue (a color call, a hand signal), react and move to receive.",
      "Finish first-time or with one touch.",
    ],
    footballWhy: "A poacher's entire game is reacting faster than the defense to a half-chance — this trains the reaction itself, not just the finishing technique.",
    coachingCue: "Stay relaxed and on the balls of your feet between cues — tensed-up waiting slows your reaction time.",
    commonMistake: "Anticipating the cue instead of genuinely reacting to it, which defeats the entire point of the drill.",
    prescription: { sets: 4, reps: "8", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Add a second, contradictory cue to increase decision complexity." },
    regression: { label: "Regression", change: "Use a predictable count instead of a random cue while learning the pattern." },
    category: "speed-agility",
    movementPatterns: ["acceleration", "change-of-direction"],
    positionGroups: ["attackers"],
    playstyles: ["poacher"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-repeated-sprint-set",
    name: "Repeated Sprint Set",
    shortDescription: "Short maximal sprints with recovery to build repeat-sprint ability.",
    execution: [
      "Sprint 20m at full effort.",
      "Walk back to the start as recovery.",
      "Repeat for the full set, holding sprint quality consistent throughout.",
    ],
    footballWhy: "An inside forward or winger's explosive runs are repeated all match, not performed once — this builds the capacity to keep them sharp late on.",
    coachingCue: "Your last sprint should look almost identical to your first — that consistency is the actual measure of fitness here.",
    commonMistake: "Sprinting the first two reps hard and quietly easing off the rest of the set.",
    prescription: { sets: 8, reps: "20m", restSeconds: 40, effortRPE: 8 },
    progression: { label: "Progression", change: "Reduce recovery to 30s or extend to 10 reps." },
    regression: { label: "Regression", change: "Reduce to 6 reps with 50s recovery." },
    category: "endurance",
    movementPatterns: ["sprint-mechanics"],
    positionGroups: ["attackers"],
    playstyles: ["inside-forward", "pressing-forward"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-repeated-pressing-sprint",
    name: "Repeated Pressing Sprint",
    shortDescription: "Sprint to close down a defender, then recover, mirroring the demands of a front-foot press.",
    execution: [
      "Start 15m from a marked defender position.",
      "Sprint to press at full intensity, arriving under control rather than sliding past.",
      "Jog back to the start as recovery and repeat.",
    ],
    footballWhy: "A pressing forward's value is measured in how many times they can repeat this exact sprint-and-arrive pattern across 90 minutes, not in a single fast press.",
    coachingCue: "Angle your press to cut off the easiest pass, not just run straight at the ball.",
    commonMistake: "Sprinting straight at the ball-carrier with no angle, which lets them simply pass around the press.",
    prescription: { sets: 6, reps: "15m", restSeconds: 40, effortRPE: 8 },
    progression: { label: "Progression", change: "Increase to 8 reps or reduce recovery to 30s." },
    regression: { label: "Regression", change: "Reduce to 4 reps with 60s recovery." },
    category: "endurance",
    movementPatterns: ["acceleration", "deceleration"],
    positionGroups: ["attackers"],
    playstyles: ["pressing-forward"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-fatigue-finishing",
    name: "High-Rep Finishing Under Fatigue",
    shortDescription: "Finishing repetitions performed right after a short sprint to simulate late-game fatigue.",
    execution: [
      "Sprint 15m to arrive at the edge of the box.",
      "Immediately receive a served ball and finish on goal.",
      "Walk back to the start as recovery and repeat.",
    ],
    footballWhy: "Real chances rarely arrive fresh — a false 9 or poacher who only finishes well when rested is missing most of the chances a real match actually creates.",
    coachingCue: "Keep your finishing technique identical to how you'd strike it fresh — fatigue is not an excuse to rush the technique.",
    commonMistake: "Rushing the shot the instant you arrive instead of taking the extra half-second needed to pick a corner.",
    prescription: { sets: 3, reps: "10", restSeconds: 60, effortRPE: 7 },
    progression: { label: "Progression", change: "Increase the sprint distance before each finish to 25m." },
    regression: { label: "Regression", change: "Reduce the sprint distance to 8m." },
    category: "endurance",
    movementPatterns: ["sprint-mechanics"],
    positionGroups: ["attackers"],
    playstyles: ["false-9", "poacher"],
    equipment: "minimal",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-movement-in-box",
    name: "Movement in the Box Circuit",
    shortDescription: "Vary near-post, far-post, and short runs, finishing each with a shot.",
    execution: [
      "Start on the edge of the box.",
      "On each rep, make a different run — near post, far post, or short in front of the defender.",
      "Finish the cross or cutback within your first touch where possible.",
    ],
    footballWhy: "A target man or poacher who only makes one type of run becomes easy to mark — varying the movement is what keeps a defense guessing.",
    coachingCue: "Commit fully to each run's direction — a half-hearted run is easy for a defender to track and cancel out.",
    commonMistake: "Making the same run every single rep instead of genuinely varying the movement pattern.",
    prescription: { sets: 3, reps: "8 each", restSeconds: 60, effortRPE: 6 },
    progression: { label: "Progression", change: "Add a marking defender reacting live to each run." },
    regression: { label: "Regression", change: "Practice one run type at a time before mixing all three." },
    category: "position-specific",
    movementPatterns: ["change-of-direction"],
    positionGroups: ["attackers"],
    playstyles: ["poacher", "target-man"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-hold-up-lay-off",
    name: "Hold-Up-and-Lay-Off Practice",
    shortDescription: "Receive with your back to goal and lay the ball off cleanly under pressure.",
    execution: [
      "Receive a firm pass with your back to a defender applying real contact.",
      "Shield the ball using your body, not your arms alone.",
      "Lay the ball off to a supporting teammate as they arrive.",
    ],
    footballWhy: "A target man or false 9 who can't hold this position under contact turns every long ball into a lost possession instead of a launched attack.",
    coachingCue: "Get your body between the ball and the defender before the ball even arrives.",
    commonMistake: "Trying to turn immediately under pressure instead of shielding and waiting for support to arrive first.",
    prescription: { sets: 3, reps: "10", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Add a second defender to increase the physical contest." },
    regression: { label: "Regression", change: "Practice the shielding body position without a live defender first." },
    category: "position-specific",
    movementPatterns: ["bracing"],
    positionGroups: ["attackers"],
    playstyles: ["target-man", "false-9"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-drop-turn-link",
    name: "Drop-and-Turn Link-Up",
    shortDescription: "Drop off the last defender to receive, then turn to attack the space just vacated.",
    execution: [
      "Start on the last defender's shoulder.",
      "Drop 5-10m to receive to feet, drawing the defender with you.",
      "Turn and either play in a supporting midfielder or drive into the space you just vacated.",
    ],
    footballWhy: "This drop-and-turn is the entire mechanism behind a false 9 — dragging a center-back out of position and then exploiting the space that decision creates.",
    coachingCue: "Time your drop to when the ball-carrier's head is up, not before — dropping too early lets the defender adjust calmly.",
    commonMistake: "Dropping so deep that you're no longer a genuine goal threat once you turn.",
    prescription: { sets: 3, reps: "8", restSeconds: 60, effortRPE: 6 },
    progression: { label: "Progression", change: "Add a live tracking center-back rather than a passive marker." },
    regression: { label: "Regression", change: "Walk through the drop-and-turn pattern with no defender first." },
    category: "position-specific",
    movementPatterns: ["rotation", "deceleration"],
    positionGroups: ["attackers"],
    playstyles: ["false-9"],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
  {
    id: "att-combination-finish",
    name: "Combination Play and Finish",
    shortDescription: "Combine with a teammate before finishing off the resulting chance.",
    execution: [
      "Start with a teammate 10m away, both facing goal.",
      "Play a one-two (or a wall pass) to beat a defender or cone.",
      "Finish the chance created within your first two touches.",
    ],
    footballWhy: "Very few real chances are created alone — training the combination and the finish together, not as two separate exercises, is what actually shows up on a match day.",
    coachingCue: "Communicate the combination before you start moving — a silent one-two is a slow one-two.",
    commonMistake: "Practicing the finish only off a straightforward pass, never off the more awkward angle a real combination actually creates.",
    prescription: { sets: 3, reps: "10", restSeconds: 45, effortRPE: 6 },
    progression: { label: "Progression", change: "Add a recovering defender to press the combination live." },
    regression: { label: "Regression", change: "Slow the combination to a walk-through pace first." },
    category: "position-specific",
    movementPatterns: ["rotation"],
    positionGroups: ["attackers"],
    playstyles: [],
    equipment: "bodyweight",
    levels: ["youth", "amateur", "advanced"],
  },
];

export const drills: Drill[] = [...shared, ...goalkeepers, ...defenders, ...midfielders, ...attackers];

export function getDrill(id: string): Drill | undefined {
  return drills.find((d) => d.id === id);
}
